---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-5.11
- name: centos-6.6
- name: centos-7.1
  # https://github.com/test-kitchen/kitchen-vagrant/issues/165
  driver_config:
    box: opscode-centos-7.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/<%= ENV.fetch("VAGRANT_DEFAULT_PROVIDER", "virtualbox") %>/opscode_centos-7.1_chef-provisionerless.box
- name: fedora-21
- name: debian-7.8
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[dnsmasq_test::default]
  attributes:
    dnsmasq:
      enable_dns: true
      enable_dhcp: true
      dhcp_options: ['dhcp-host=01:23:ab:cd:01:02,larry,10.0.0.10']
      dns:
        server: '8.8.8.8'
      dhcp:
        dhcp-range: 'eth1,10.0.0.5,10.0.0.15,12h'
        domain: 'test.lab'
        tftp-root: '/var/lib/tftpboot'
        enable-tftp: null
        interface: 'eth1'
